CREATE TABLE `background_jobs` (
	`id` bigint unsigned AUTO_INCREMENT NOT NULL,
	`family_id` bigint unsigned NOT NULL,
	`media_id` bigint unsigned NOT NULL,
	`generation` bigint unsigned NOT NULL,
	`recipe_id` smallint unsigned NOT NULL,
	`job_type` enum('MEDIA_PROBE','IMAGE_DERIVATIVES','VIDEO_POSTER') NOT NULL,
	`state` enum('QUEUED','RUNNING','RETRY_WAIT','SUCCEEDED','FAILED','CANCELLED') NOT NULL DEFAULT 'QUEUED',
	`attempts` tinyint unsigned NOT NULL DEFAULT 0,
	`max_attempts` tinyint unsigned NOT NULL DEFAULT 3,
	`available_at` datetime(3) NOT NULL,
	`locked_at` datetime(3),
	`heartbeat_at` datetime(3),
	`locked_until` datetime(3),
	`worker_id` binary(16),
	`lease_epoch` bigint unsigned NOT NULL DEFAULT 0,
	`last_failure_code` enum('UNSUPPORTED_FORMAT','CAPABILITY_UNAVAILABLE','MALFORMED_MEDIA','INPUT_LIMIT','OUTPUT_LIMIT','PROCESS_TIMEOUT','RESOURCE_LIMIT','TEMPORARY_IO','STORAGE_UNAVAILABLE','ORIGINAL_MISSING','ORIGINAL_CORRUPT','DERIVED_INTEGRITY','WORKER_LOST','DB_UNAVAILABLE','COMMIT_OUTCOME_UNKNOWN'),
	`created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`finished_at` datetime(3),
	CONSTRAINT `background_jobs_id` PRIMARY KEY(`id`),
	CONSTRAINT `uq_background_jobs_identity` UNIQUE(`family_id`,`media_id`,`generation`,`recipe_id`,`job_type`),
	CONSTRAINT `uq_background_jobs_family_media_id` UNIQUE(`family_id`,`media_id`,`id`),
	CONSTRAINT `chk_background_jobs_generation` CHECK(`background_jobs`.`generation` >= 1),
	CONSTRAINT `chk_background_jobs_recipe` CHECK(`background_jobs`.`recipe_id` >= 1),
	CONSTRAINT `chk_background_jobs_attempts` CHECK(`background_jobs`.`attempts` <= `background_jobs`.`max_attempts` AND `background_jobs`.`max_attempts` BETWEEN 1 AND 3),
	CONSTRAINT `chk_background_jobs_lease` CHECK((`background_jobs`.`state` = 'RUNNING' AND `background_jobs`.`locked_at` IS NOT NULL AND `background_jobs`.`heartbeat_at` IS NOT NULL AND `background_jobs`.`locked_until` IS NOT NULL AND `background_jobs`.`worker_id` IS NOT NULL AND `background_jobs`.`lease_epoch` > 0 AND `background_jobs`.`locked_at` <= `background_jobs`.`heartbeat_at` AND `background_jobs`.`heartbeat_at` < `background_jobs`.`locked_until`) OR (`background_jobs`.`state` <> 'RUNNING' AND `background_jobs`.`locked_at` IS NULL AND `background_jobs`.`heartbeat_at` IS NULL AND `background_jobs`.`locked_until` IS NULL AND `background_jobs`.`worker_id` IS NULL)),
	CONSTRAINT `chk_background_jobs_terminal` CHECK((`background_jobs`.`state` IN ('SUCCEEDED','FAILED','CANCELLED') AND `background_jobs`.`finished_at` IS NOT NULL AND `background_jobs`.`finished_at` >= `background_jobs`.`created_at`) OR (`background_jobs`.`state` NOT IN ('SUCCEEDED','FAILED','CANCELLED') AND `background_jobs`.`finished_at` IS NULL)),
	CONSTRAINT `chk_background_jobs_failure` CHECK((`background_jobs`.`state` IN ('FAILED','RETRY_WAIT') AND `background_jobs`.`last_failure_code` IS NOT NULL) OR (`background_jobs`.`state` IN ('QUEUED','SUCCEEDED','CANCELLED') AND `background_jobs`.`last_failure_code` IS NULL) OR `background_jobs`.`state` = 'RUNNING')
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--> statement-breakpoint
CREATE TABLE `derived_assets` (
	`id` bigint unsigned AUTO_INCREMENT NOT NULL,
	`family_id` bigint unsigned NOT NULL,
	`media_id` bigint unsigned NOT NULL,
	`generation` bigint unsigned NOT NULL,
	`recipe_id` smallint unsigned NOT NULL,
	`kind` enum('THUMBNAIL','PREVIEW','VIDEO_POSTER') NOT NULL,
	`state` enum('RESERVED','PUBLISHING','READY','MISSING','FAILED') NOT NULL DEFAULT 'RESERVED',
	`reserved_bytes` bigint unsigned NOT NULL,
	`byte_size` bigint unsigned,
	`sha256` binary(32),
	`width` int unsigned,
	`height` int unsigned,
	`output_mime` varchar(127),
	`producer_job_id` bigint unsigned NOT NULL,
	`producer_lease_epoch` bigint unsigned,
	`failure_code` enum('UNSUPPORTED_FORMAT','CAPABILITY_UNAVAILABLE','MALFORMED_MEDIA','INPUT_LIMIT','OUTPUT_LIMIT','PROCESS_TIMEOUT','RESOURCE_LIMIT','TEMPORARY_IO','STORAGE_UNAVAILABLE','ORIGINAL_MISSING','ORIGINAL_CORRUPT','DERIVED_INTEGRITY','WORKER_LOST','DB_UNAVAILABLE','COMMIT_OUTCOME_UNKNOWN'),
	`published_at` datetime(3),
	`cleaned_at` datetime(3),
	`created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	CONSTRAINT `derived_assets_id` PRIMARY KEY(`id`),
	CONSTRAINT `uq_derived_assets_identity` UNIQUE(`family_id`,`media_id`,`generation`,`recipe_id`,`kind`),
	CONSTRAINT `chk_derived_assets_generation` CHECK(`derived_assets`.`generation` >= 1),
	CONSTRAINT `chk_derived_assets_recipe` CHECK(`derived_assets`.`recipe_id` >= 1),
	CONSTRAINT `chk_derived_assets_reservation` CHECK((`derived_assets`.`kind` = 'THUMBNAIL' AND `derived_assets`.`reserved_bytes` BETWEEN 1 AND 524288) OR (`derived_assets`.`kind` = 'PREVIEW' AND `derived_assets`.`reserved_bytes` BETWEEN 1 AND 4194304) OR (`derived_assets`.`kind` = 'VIDEO_POSTER' AND `derived_assets`.`reserved_bytes` BETWEEN 1 AND 1048576)),
	CONSTRAINT `chk_derived_assets_bytes_digest` CHECK((`derived_assets`.`byte_size` IS NULL AND `derived_assets`.`sha256` IS NULL) OR (`derived_assets`.`byte_size` IS NOT NULL AND `derived_assets`.`sha256` IS NOT NULL AND `derived_assets`.`byte_size` > 0 AND `derived_assets`.`byte_size` <= `derived_assets`.`reserved_bytes`)),
	CONSTRAINT `chk_derived_assets_dimensions` CHECK((`derived_assets`.`width` IS NULL AND `derived_assets`.`height` IS NULL) OR (`derived_assets`.`width` IS NOT NULL AND `derived_assets`.`height` IS NOT NULL AND `derived_assets`.`width` > 0 AND `derived_assets`.`height` > 0)),
	CONSTRAINT `chk_derived_assets_published_payload` CHECK(`derived_assets`.`state` NOT IN ('PUBLISHING','READY') OR (`derived_assets`.`byte_size` IS NOT NULL AND `derived_assets`.`sha256` IS NOT NULL AND `derived_assets`.`width` IS NOT NULL AND `derived_assets`.`height` IS NOT NULL AND `derived_assets`.`output_mime` = 'image/webp' AND `derived_assets`.`producer_lease_epoch` IS NOT NULL AND `derived_assets`.`producer_lease_epoch` > 0)),
	CONSTRAINT `chk_derived_assets_ready` CHECK(`derived_assets`.`state` <> 'READY' OR (`derived_assets`.`published_at` IS NOT NULL AND `derived_assets`.`cleaned_at` IS NULL AND `derived_assets`.`published_at` >= `derived_assets`.`created_at`)),
	CONSTRAINT `chk_derived_assets_failure` CHECK((`derived_assets`.`state` IN ('MISSING','FAILED') AND `derived_assets`.`failure_code` IS NOT NULL) OR (`derived_assets`.`state` NOT IN ('MISSING','FAILED') AND `derived_assets`.`failure_code` IS NULL)),
	CONSTRAINT `chk_derived_assets_times` CHECK((`derived_assets`.`published_at` IS NULL OR `derived_assets`.`published_at` >= `derived_assets`.`created_at`) AND (`derived_assets`.`cleaned_at` IS NULL OR `derived_assets`.`cleaned_at` >= `derived_assets`.`created_at`))
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--> statement-breakpoint
CREATE TABLE `media_items` (
	`id` bigint unsigned AUTO_INCREMENT NOT NULL,
	`family_id` bigint unsigned NOT NULL,
	`storage_object_id` bigint unsigned NOT NULL,
	`source_upload_id` bigint unsigned NOT NULL,
	`uploaded_at` datetime(3) NOT NULL,
	`media_type` enum('UNKNOWN','IMAGE','VIDEO','OTHER') NOT NULL DEFAULT 'UNKNOWN',
	`detected_mime` varchar(127),
	`processing_state` enum('PENDING','PROCESSING','READY','PARTIAL','FAILED','BLOCKED') NOT NULL DEFAULT 'PENDING',
	`generation` bigint unsigned NOT NULL DEFAULT 1,
	`recipe_id` smallint unsigned NOT NULL DEFAULT 1,
	`metadata_generation` bigint unsigned,
	`raw_width` int unsigned,
	`raw_height` int unsigned,
	`display_width` int unsigned,
	`display_height` int unsigned,
	`duration_ms` bigint unsigned,
	`orientation` tinyint unsigned,
	`video_rotation_degrees` smallint,
	`is_animated` boolean NOT NULL DEFAULT false,
	`motion_hint` boolean NOT NULL DEFAULT false,
	`captured_local_at` datetime(3),
	`captured_at_utc` datetime(3),
	`captured_offset_minutes` smallint,
	`captured_source` enum('NONE','EXIF_ORIGINAL','EXIF_CREATE','XMP_ORIGINAL','XMP_CREATE','QUICKTIME_CREATION','CONTAINER_CREATION') NOT NULL DEFAULT 'NONE',
	`captured_time_status` enum('ABSENT','OFFSET_KNOWN','OFFSET_UNKNOWN') NOT NULL DEFAULT 'ABSENT',
	`timeline_key` datetime(3) NOT NULL,
	`timeline_basis` enum('CAPTURE_LOCAL','UPLOAD_UTC') NOT NULL DEFAULT 'UPLOAD_UTC',
	`gps_latitude` decimal(9,6),
	`gps_longitude` decimal(10,6),
	`camera_make` varchar(128),
	`camera_model` varchar(128),
	`video_codec` varchar(32),
	`video_container` varchar(32),
	`video_transfer` varchar(32),
	`warning_flags` bigint unsigned NOT NULL DEFAULT 0,
	`last_failure_code` enum('UNSUPPORTED_FORMAT','CAPABILITY_UNAVAILABLE','MALFORMED_MEDIA','INPUT_LIMIT','OUTPUT_LIMIT','PROCESS_TIMEOUT','RESOURCE_LIMIT','TEMPORARY_IO','STORAGE_UNAVAILABLE','ORIGINAL_MISSING','ORIGINAL_CORRUPT','DERIVED_INTEGRITY','WORKER_LOST','DB_UNAVAILABLE','COMMIT_OUTCOME_UNKNOWN'),
	`created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	CONSTRAINT `media_items_id` PRIMARY KEY(`id`),
	CONSTRAINT `uq_media_items_family_storage_object` UNIQUE(`family_id`,`storage_object_id`),
	CONSTRAINT `uq_media_items_family_id` UNIQUE(`family_id`,`id`),
	CONSTRAINT `chk_media_items_generation` CHECK(`media_items`.`generation` >= 1),
	CONSTRAINT `chk_media_items_recipe` CHECK(`media_items`.`recipe_id` >= 1),
	CONSTRAINT `chk_media_items_metadata_generation` CHECK(`media_items`.`metadata_generation` IS NULL OR (`media_items`.`metadata_generation` >= 1 AND `media_items`.`metadata_generation` <= `media_items`.`generation`)),
	CONSTRAINT `chk_media_items_raw_dimensions` CHECK((`media_items`.`raw_width` IS NULL AND `media_items`.`raw_height` IS NULL) OR (`media_items`.`raw_width` IS NOT NULL AND `media_items`.`raw_height` IS NOT NULL AND `media_items`.`raw_width` > 0 AND `media_items`.`raw_height` > 0)),
	CONSTRAINT `chk_media_items_display_dimensions` CHECK((`media_items`.`display_width` IS NULL AND `media_items`.`display_height` IS NULL) OR (`media_items`.`display_width` IS NOT NULL AND `media_items`.`display_height` IS NOT NULL AND `media_items`.`display_width` > 0 AND `media_items`.`display_height` > 0)),
	CONSTRAINT `chk_media_items_duration` CHECK(`media_items`.`duration_ms` IS NULL OR `media_items`.`duration_ms` <= 86400000),
	CONSTRAINT `chk_media_items_orientation` CHECK(`media_items`.`orientation` IS NULL OR `media_items`.`orientation` BETWEEN 1 AND 8),
	CONSTRAINT `chk_media_items_video_rotation` CHECK(`media_items`.`video_rotation_degrees` IS NULL OR `media_items`.`video_rotation_degrees` IN (0,90,180,270)),
	CONSTRAINT `chk_media_items_animated_boolean` CHECK(`media_items`.`is_animated` IN (0,1)),
	CONSTRAINT `chk_media_items_motion_boolean` CHECK(`media_items`.`motion_hint` IN (0,1)),
	CONSTRAINT `chk_media_items_gps` CHECK((`media_items`.`gps_latitude` IS NULL AND `media_items`.`gps_longitude` IS NULL) OR (`media_items`.`gps_latitude` IS NOT NULL AND `media_items`.`gps_longitude` IS NOT NULL AND `media_items`.`gps_latitude` BETWEEN -90 AND 90 AND `media_items`.`gps_longitude` BETWEEN -180 AND 180)),
	CONSTRAINT `chk_media_items_capture` CHECK((`media_items`.`captured_time_status` = 'ABSENT' AND `media_items`.`captured_source` = 'NONE' AND `media_items`.`captured_local_at` IS NULL AND `media_items`.`captured_at_utc` IS NULL AND `media_items`.`captured_offset_minutes` IS NULL) OR (`media_items`.`captured_time_status` = 'OFFSET_UNKNOWN' AND `media_items`.`captured_source` <> 'NONE' AND `media_items`.`captured_local_at` IS NOT NULL AND `media_items`.`captured_at_utc` IS NULL AND `media_items`.`captured_offset_minutes` IS NULL) OR (`media_items`.`captured_time_status` = 'OFFSET_KNOWN' AND `media_items`.`captured_source` <> 'NONE' AND `media_items`.`captured_local_at` IS NOT NULL AND `media_items`.`captured_at_utc` IS NOT NULL AND `media_items`.`captured_offset_minutes` IS NOT NULL AND `media_items`.`captured_offset_minutes` BETWEEN -840 AND 840 AND (ABS(`media_items`.`captured_offset_minutes`) < 840 OR MOD(`media_items`.`captured_offset_minutes`,60) = 0))),
	CONSTRAINT `chk_media_items_timeline` CHECK((`media_items`.`timeline_basis` = 'CAPTURE_LOCAL' AND `media_items`.`captured_local_at` IS NOT NULL AND `media_items`.`timeline_key` = `media_items`.`captured_local_at`) OR (`media_items`.`timeline_basis` = 'UPLOAD_UTC' AND `media_items`.`timeline_key` = `media_items`.`uploaded_at`)),
	CONSTRAINT `chk_media_items_ready_metadata` CHECK(`media_items`.`processing_state` <> 'READY' OR (`media_items`.`metadata_generation` IS NOT NULL AND `media_items`.`metadata_generation` = `media_items`.`generation`)),
	CONSTRAINT `chk_media_items_warning_flags` CHECK(`media_items`.`warning_flags` <= 255),
	CONSTRAINT `chk_media_items_failure` CHECK((`media_items`.`processing_state` IN ('FAILED','BLOCKED') AND `media_items`.`last_failure_code` IS NOT NULL) OR (`media_items`.`processing_state` NOT IN ('FAILED','BLOCKED') AND (`media_items`.`processing_state` = 'PARTIAL' OR `media_items`.`last_failure_code` IS NULL)))
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--> statement-breakpoint
ALTER TABLE `upload_sessions` ADD CONSTRAINT `uq_upload_sessions_family_id_object` UNIQUE(`family_id`,`id`,`storage_object_id`);--> statement-breakpoint
ALTER TABLE `background_jobs` ADD CONSTRAINT `fk_background_jobs_media` FOREIGN KEY (`family_id`,`media_id`) REFERENCES `media_items`(`family_id`,`id`) ON DELETE restrict ON UPDATE restrict;--> statement-breakpoint
ALTER TABLE `derived_assets` ADD CONSTRAINT `fk_derived_assets_media` FOREIGN KEY (`family_id`,`media_id`) REFERENCES `media_items`(`family_id`,`id`) ON DELETE restrict ON UPDATE restrict;--> statement-breakpoint
ALTER TABLE `derived_assets` ADD CONSTRAINT `fk_derived_assets_producer_job` FOREIGN KEY (`family_id`,`media_id`,`producer_job_id`) REFERENCES `background_jobs`(`family_id`,`media_id`,`id`) ON DELETE restrict ON UPDATE restrict;--> statement-breakpoint
ALTER TABLE `media_items` ADD CONSTRAINT `fk_media_items_storage_object` FOREIGN KEY (`family_id`,`storage_object_id`) REFERENCES `storage_objects`(`family_id`,`id`) ON DELETE restrict ON UPDATE restrict;--> statement-breakpoint
ALTER TABLE `media_items` ADD CONSTRAINT `fk_media_items_source_upload` FOREIGN KEY (`family_id`,`source_upload_id`,`storage_object_id`) REFERENCES `upload_sessions`(`family_id`,`id`,`storage_object_id`) ON DELETE restrict ON UPDATE restrict;--> statement-breakpoint
CREATE INDEX `idx_background_jobs_claim` ON `background_jobs` (`state`,`available_at`,`id`);--> statement-breakpoint
CREATE INDEX `idx_background_jobs_lease` ON `background_jobs` (`state`,`locked_until`,`id`);--> statement-breakpoint
CREATE INDEX `idx_derived_assets_state` ON `derived_assets` (`state`,`id`);--> statement-breakpoint
CREATE INDEX `idx_derived_assets_cleanup` ON `derived_assets` (`family_id`,`cleaned_at`,`state`,`id`);--> statement-breakpoint
CREATE INDEX `idx_media_items_family_timeline` ON `media_items` (`family_id`,`timeline_key`,`id`);--> statement-breakpoint
CREATE INDEX `idx_media_items_processing` ON `media_items` (`processing_state`,`id`);
